Repository w3c/dapt, pull requests merged in 2024-03, with the labels that each got.

#158 clarify what spans are possible in a text and how they are handled
  index.html
Labels: agenda

#225 Add at-risk features
  index.html
Labels: editorial, CR must-have

#226 Note use case for missing Text objects, and define empty Text
  index.html
Labels: editorial
